### ISSUE TITLE
Puzzle 9610805 ("Cat") fails to load

### ISSUE THREAD

**Issue by Omei** [eternagame/EternaJS#220]
Regression: https://eternagame.org/game/puzzle/9610805/, which was created on 11/22/19  and solved 9 times, now crashes. Occurs on both chrome and Firefox.
![Cat  call stack](https://user-images.githubusercontent.com/5702744/72302462-f4129a00-361e-11ea-8bde-8a11ecff03d6.png)

**Comment by luxaritas** [comment]
This is due to a bad tutorial script. We need to implement proper validation (see #9). Historically our position has been not to do anything about this since it is user generated content and we didn't want to just arbitrarily change it. We may want to change that stance to having an admin wipe the script and sending it to the author in a PM with a message explaining why, but this is neither a bug (beyond #9, as I mentioned before) nor a regression.
