### ISSUE TITLE
Scroll wheel perform zoom rather than scroll

### ISSUE THREAD

**Issue by BurtHarris** [eternagame/EternaJS#224]
Most applications treat use of the mouse wheel as a scroll controller in the y dimension.   Some mice have a side-to-side motion available on the wheel, which is generally used for x dimension scrolling (where appropriate).   

EneRNAjs on the other hand has somehow ended up with the scroll wheel being a zoom level controller, which is inconsistent with many other applications.   The normal convention since Microsoft made the scroll wheel popular has been that Ctrl+ScrollWheel was used for zooming.

Even more confusing, when using EteRNAjs, using Ctrl+ScrollWheel in fact results in a different style of zooming, generally implemented by browsers.

See https://en.wikipedia.org/wiki/Scroll_wheel.

What would you think of adopting the more conventional approach of having scroll wheel perform horizontal scrolling, unless modified by a Ctrl key?

**Comment by BurtHarris** [comment]
There certainly are other popular apps which use the mouse wheel for zoom level, Google Maps and Bing Maps come to mind.    However both Maps apps seems to work consistantly weather or not the Ctrl key is held down, and they seem to do this by disabling the browsers zoom functionality through the mouse wheel.

**Comment by Omei** [comment]
From my personal experience, I would have described the conventional use as
-  If there are vertical scroll bars, the scroll wheel scrolls vertically.
- If there are no vertical scroll bars, and it makes sense to zoom in/out, that's what the scroll bar does.

**Comment by luxaritas** [comment]
I think I’m with Omei here. Additional thoughts: * Apps that use mouse-based panning often use scroll for zoom.
* Zooming is generally more “useful” since you can pan by mouse
* This would be a very significant and unintuitive change for current users
* I would possibly be a proponent of using some combination of ctrl+wheel/shift+wheel/alt+wheel for vertical and horizontal zoom (I think this is semi-standard)
* On a high level at least I agree that we should disable browser zoom. It’s lead to a lot of people encountering extremely counterintuitive bugs and layout issues. However one concern I have is for accessibility - those with vision impairment might need a larger UI, and might default to using browser zoom for that. That said, again, as-is it creates really bad layout bugs that might just make things worse. I’ve seen OS-based magnifiers used, but we might also want to add some sort of “UI magnification” option to actually increase the size of UI elements, especially once we can work out a proper UI for smaller screen sizes ie mobile (since it’s effectively the same issue)

**Comment by BurtHarris** [comment]
OK, I'll close this based primarily on the **very significant and unintuitive change for current users** argument.    

Thanks
