### ISSUE TITLE
Vienna[2] dot plot probabilities are sqrt(true prob)

### ISSUE THREAD

**Issue by everyday847** [eternagame/EternaJS#291]
This causes a bifurcation of behavior in `updateMeltingPointAndDotPlot` for calculating particular important scoring features like the base pair proximity and the mean probability unpaired: we have to track what the folder is in order to transform the data properly. We do NOT yet do anything for the bpps themselves, because we want to ensure dot plots stay looking nice + EternaBot isn't affected.

**Comment by ElNando888** [comment]
This can be deduced from the code, but here's why this sqrt() has been in there for so long.

ViennaRNA has code to generate dotplots. This uses PostScript templates, and the guys at TBI chose to reject gray-scales in favor of using pure black square dots centered within white unit squares. How do you represent a 0.5 probability? You need to cover 0.5 of the white unit surface with black ink, so you gonna use a square with a side of length... sqrt(0.5).

ViennaRNA had other APIs to access pairing probabilities, but back in 2011 (or so) Jeehyung Lee needed the data for basically the same purpose, displaying a graphic in the game. So he reused ViennaRNA's printing code, and instead of making little black squares inside of white ones (which doesn't render well on screen), he took the data and converted it to a gray-scale directly (without squaring back to the original values). The effect is close to a gamma-correction, and I mistook it for just that for a while. But it's not, it's an old mistake.

**Comment by everyday847** [comment]
That's also a gratifying explanation for why Vienna's getDotPlot function returns a postscript string that then gets parsed. Thank you for preserving this wisdom!

**Comment by everyday847** [comment]
This qualifies as a "fact" rather than an "issue." Thank you again, @ElNando888 !
