### ISSUE TITLE
Investigate PixiJS Legacy with Pixi v5 upgrade

### ISSUE THREAD

**Issue by luxaritas** [eternagame/EternaJS#373]
While ideally we'd only support WebGL, I can imagine a number of instances where that could be an issue (broken graphics drivers, older computers, etc). I'd like to investigate using pixijs-legacy to provide fallback canvas support. If this is ultimately not viable, we'll need to add detecting this feature to our checks on the game page that show the banner if support isnt available

**Comment by everyday847** [comment]
This suggests it might be a very simple change:

https://stackoverflow.com/questions/61638676/create-legacy-fallback-for-pixi-js

Since it's a simple change, I'd _personally_ rather see it as a priority for v1.9.1: if we get feedback that there are a lot of players who can't use a modern browser (!) then we can make it pretty quickly, but I'd like to prioritize urgent usability/feature requests for v1.9.

**Comment by luxaritas** [comment]
Remember the issue here is not really modern browser - the issue is having broken/old graphics drivers, which I have encountered in the wild a few times.

**Comment by luxaritas** [comment]
Things have gone smoothly enough that I'm going to move toward doing a support check like we do with WebGL and linking a troubleshooting guide in the forums. Apparently one of the issues people have run into is just not having hardware acceleration enabled, which is an easy fix as long as you're aware of it. Started this process by exposing Pixi's compatibility check (`Pixi.utils.isWebGLSupported`) in cc1422d.

Once I get 1.9.1 deployed I think I'll look at integrating the compatibility check we currently do in the website code into the game itself, throwing some text in the game div or such. That way when it's embedded in different contexts, we still get the error checking. That being said, the PIXI method doesn't really need to be exposed, does it! I'll backtrack and revert that change,
