### ISSUE TITLE
Fix sequence similarity sort in new browser

### ISSUE THREAD

**Issue by luxaritas** [eternagame/EternaJS#379]
It appears that Amine though this was just sort by sequence, but in fact it is functionality that was provided by another button

**Comment by everyday847** [comment]
Actually, we're both wrong. I thought the bug was also present in 1.8.5, you thought it was newly introduced by the DesignBrowser. Look at this:

```
    private sortOnSolution(solution: Solution): void {
        this.closeCurDialog();
        this._sortOptions.addCriteria(DesignCategory.SEQUENCE, SortOrder.INCREASING, solution.sequence);
        this.showSortDialog();
    }
```

The sequence arg supplied third actually changes the semantics of `addCriteria` entirely (thank goodness!). `SortOptions::compareSolutions` is your guide.
