### ISSUE TITLE
Annotations crash

### ISSUE THREAD

**Issue by Omei** [eternagame/EternaJS#584]
I tried creating annotations on an R4 23S puzzle solution I had submitted - https://eternagame.org/game/browse/10915916/?filter1=Id&filter1_arg1=11047264&filter1_arg2=11047264. Unfortunately, I couldn't get far without creating fatal errors that killed all UI interaction.

I haven't pinned down the necessary and sufficient conditions needed to trigger this. I was able to add some multi-segment annotations and even one with three segments, each segment being just one base.  But every attempt I made to create an annotation for the PTC-ring (which is a 6-way junction) that included more than 2 segment ranges (of the 6 desired) immediately triggered the error when I first tried to save it.

Once the error occurs, the puzzle is dead because any attempt at interacting with the puzzle simply causes the same errors.

![Undefined property errors in 23S](https://user-images.githubusercontent.com/5702744/140437727-36f2da7e-d6fc-4e3c-86c0-0ecbffe180a1.png)
s.

**Comment by luxaritas** [comment]
Looks like this happens when the annotation manager can't find a usable location for an annotation. If you only have one range, this is generally a nonissue - it just doesn't display it (which admittedly still isn't great). However, due to the caching behavior, when it goes to re-render, because there are positions for some ranges but not others, it assumes they all have ranges, and winds up trying to access an object that doesn't exist.

I'm following through with that fix, such that if a given range doesn't have a valid position, we ignore that range rather than crashing, with the understanding that we need to revisit the position computation to not give up in the way that it does now.

Note: Reproduced on puzzle 10907949 with zoomLevel 2 and annotation range `1833-1833, 1835-1835, 1905-1905, 1929-1929, 1934-1934, 1936-1936, 1940-1940, 1965-1965, 1968-1968, 1972-1972`
