### ISSUE TITLE
Disappearing structure objective on Fluorescent Probes 1 (but not similar puzzles)

### ISSUE THREAD

**Issue by sbutkovi** [eternagame/EternaJS#652]
This behavior was observed on Dev and on Prod using Chrome on Windows. This behavior was also observed on mobile app version 1.5.0.

The structure objective for the 2nd state can be seen behind the intro screen:

![pic1](https://user-images.githubusercontent.com/35237235/172955353-38e6a35a-2d78-4f1d-b815-ec5854148b20.PNG)

However, this objective mysteriously disappears upon entering the puzzle:

![pic2](https://user-images.githubusercontent.com/35237235/172955368-acfcb821-e064-4947-92dc-57bc4369025b.png)

It is worth noting that this issue does not occur within similar puzzles within the Fluorescent Probes series, at least on Dev (example screenshot below):

![pic3](https://user-images.githubusercontent.com/35237235/172955503-c715c6a6-85bd-4123-bc69-20bacec69be3.png)

**Comment by luxaritas** [comment]
It appears that this is "intentional" due to the tutorial script, which hides the switcher, pip mode, and the second structure constraint. I think the intention was to be able to temporarily show the molecule without actually introducing the idea of a switch. 

There are two ways of resolving this (barring a way to temporarily introduce a molecule, which is not something that can be done in the near future):
1) Change the tutorial script to not do this
2) "Fix" the interface so that the second target isn't shown on the intro screen and there isn't extra space delegated for it in the constraint container

@sbutkovi I'll leave it up to you for how we should proceed

**Comment by sbutkovi** [comment]
I'll probably just change the tutorial script. I'll update this issue once that's complete.

**Comment by sbutkovi** [comment]
I updated the tutorial script, and the issue seems to be resolved.
